vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        image_file:
            # alias qui nous permet d'accéder à nos images depuis le navigateur
            uri_prefix: /images/cards
            # Chemin vers le dossier de stockage
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false